//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskDispatchManager.DBModels.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpressProcessDetail
    {
        public System.Guid Guid { get; set; }
        public Nullable<int> GroupNo { get; set; }
        public string ExpressNo { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
        public string Context { get; set; }
        public Nullable<byte> State { get; set; }
    }
}
