//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskDispatchManager.DBModels.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public System.Guid Guid { get; set; }
        public string Receiver { get; set; }
        public string Content { get; set; }
        public string Subject { get; set; }
        public Nullable<byte> Type { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string FromType { get; set; }
        public Nullable<System.Guid> FkGUID { get; set; }
    }
}
