//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskDispatchManager.DBModels.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proxy
    {
        public System.Guid Guid { get; set; }
        public string Country { get; set; }
        public string IP { get; set; }
        public string Port { get; set; }
        public string ProxyIp { get; set; }
        public string Position { get; set; }
        public string Anonymity { get; set; }
        public string Type { get; set; }
        public string Speed { get; set; }
        public string ConnectTime { get; set; }
        public string VerifyTime { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public bool IsDelete { get; set; }
    }
}
